In [266]:
import json
import os

!mkdir /root/.kaggle/
# Installing the Kaggle package

#Important Note: complete this with your own key - after running this for the first time remmember to **remove** your API_KEY
api_token = {"username":"ehudvaknin","key":"91a60e512d3104516c20766375466113"}

# creating kaggle.json file with the personal API-Key details
# You can also put this file on your Google Drive

with open('/root/.kaggle/kaggle.json', 'w') as file:
  json.dump(api_token, file)
!chmod 600 /root/.kaggle/kaggle.json

mkdir: cannot create directory ‘/root/.kaggle/’: File exists


In [270]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv("/content/kc_house_data.csv")
df.head()

id             date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000  221900.0         3       1.00         1180   
1  6414100192  20141209T000000  538000.0         3       2.25         2570   
2  5631500400  20150225T000000  180000.0         2       1.00          770   
3  2487200875  20141209T000000  604000.0         4       3.00         1960   
4  1954400510  20150218T000000  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  

[5 rows x 21 columns]

In [271]:
# Pre-Processing
df = df.drop(['id', 'date', 'zipcode'], axis=1)
df.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0  221900.0         3       1.00         1180      5650     1.0           0   
1  538000.0         3       2.25         2570      7242     2.0           0   
2  180000.0         2       1.00          770     10000     1.0           0   
3  604000.0         4       3.00         1960      5000     1.0           0   
4  510000.0         3       2.00         1680      8080     1.0           0   

   view  condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
0     0          3      7        1180              0      1955             0   
1     0          3      7        2170            400      1951          1991   
2     0          3      6         770              0      1933             0   
3     0          5      7        1050            910      1965             0   
4     0          3      8        1680              0      1987             0   

       lat     long  sqft_living15  sqft_lot15  
0  47.5112 -122.257           1340        5650  
1  47.7210 -122.319           1690        7639  
2  47.7379 -122.233           2720        8062  
3  47.5208 -122.393           1360        5000  
4  47.6168 -122.045           1800        7503

In [272]:
df.describe()

price      bedrooms     bathrooms   sqft_living      sqft_lot  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  2.161300e+04   
mean   5.400881e+05      3.370842      2.114757   2079.899736  1.510697e+04   
std    3.671272e+05      0.930062      0.770163    918.440897  4.142051e+04   
min    7.500000e+04      0.000000      0.000000    290.000000  5.200000e+02   
25%    3.219500e+05      3.000000      1.750000   1427.000000  5.040000e+03   
50%    4.500000e+05      3.000000      2.250000   1910.000000  7.618000e+03   
75%    6.450000e+05      4.000000      2.500000   2550.000000  1.068800e+04   
max    7.700000e+06     33.000000      8.000000  13540.000000  1.651359e+06   

             floors    waterfront          view     condition         grade  \
count  21613.000000  21613.000000  21613.000000  21613.000000  21613.000000   
mean       1.494309      0.007542      0.234303      3.409430      7.656873   
std        0.539989      0.086517      0.766318      0.650743      1.175459   
min        1.000000      0.000000      0.000000      1.000000      1.000000   
25%        1.000000      0.000000      0.000000      3.000000      7.000000   
50%        1.500000      0.000000      0.000000      3.000000      7.000000   
75%        2.000000      0.000000      0.000000      4.000000      8.000000   
max        3.500000      1.000000      4.000000      5.000000     13.000000   

         sqft_above  sqft_basement      yr_built  yr_renovated           lat  \
count  21613.000000   21613.000000  21613.000000  21613.000000  21613.000000   
mean    1788.390691     291.509045   1971.005136     84.402258     47.560053   
std      828.090978     442.575043     29.373411    401.679240      0.138564   
min      290.000000       0.000000   1900.000000      0.000000     47.155900   
25%     1190.000000       0.000000   1951.000000      0.000000     47.471000   
50%     1560.000000       0.000000   1975.000000      0.000000     47.571800   
75%     2210.000000     560.000000   1997.000000      0.000000     47.678000   
max     9410.000000    4820.000000   2015.000000   2015.000000     47.777600   

               long  sqft_living15     sqft_lot15  
count  21613.000000   21613.000000   21613.000000  
mean    -122.213896    1986.552492   12768.455652  
std        0.140828     685.391304   27304.179631  
min     -122.519000     399.000000     651.000000  
25%     -122.328000    1490.000000    5100.000000  
50%     -122.230000    1840.000000    7620.000000  
75%     -122.125000    2360.000000   10083.000000  
max     -121.315000    6210.000000  871200.000000

In [274]:
# Analyze lat,long columns -> if necessary : keep, else : remove
import geopy
from geopy.geocoders import Nominatim
from typing import Optional
geolocator = Nominatim(user_agent="house_pricing")
def reverse_geocode(lat: float, long: float, state_city: Optional[str] = None) -> str:
    if state_city is not None and state_city not in [np.nan]:
        print(f"Location of {lat}, {long} already exists: {state_city}")
        return state_city
    location = geolocator.reverse((lat, long), timeout=1000)
    address = location.address
    # Extract city and state from the address
    city = location.raw['address'].get('city', '')
    state = location.raw['address'].get('state', '')
    print(f"Location of {lat}, {long}: {state}, {city}")
    return f"{state}, {city}"

lat_col = df['lat'][0]
long_col = df['long'][0]

for start_index in range(0, len(df)//1000, 10):
    end_index = start_index + 10
    df.loc[start_index:end_index, 'state_city'] = df.loc[start_index:end_index].apply(
      lambda row: reverse_geocode(row['lat'], row['long'], row.get('state_city')),axis=1)

    df.to_csv("/content/house_locations.csv")

Location of 47.5112, -122.257 already exists: Washington, Seattle
Location of 47.721, -122.319 already exists: Washington, Seattle
Location of 47.7379, -122.233 already exists: Washington, 
Location of 47.5208, -122.393 already exists: Washington, Seattle
Location of 47.6168, -122.045 already exists: Washington, 
Location of 47.6561, -122.005 already exists: Washington, 
Location of 47.3097, -122.327 already exists: Washington, 
Location of 47.4095, -122.315 already exists: Washington, 
Location of 47.5123, -122.337 already exists: Washington, Seattle
Location of 47.3684, -122.031 already exists: Washington, 
Location of 47.6007, -122.145 already exists: Washington, Bellevue
Location of 47.6007, -122.145 already exists: Washington, Bellevue
Location of 47.69, -122.292: Washington, Seattle
Location of 47.7558, -122.229: Washington, 
Location of 47.6127, -122.045: Washington, 
Location of 47.67, -122.394: Washington, Seattle
Location of 47.5714, -122.375: Washington, Seattle
Location of 

In [275]:
# All house located in Washington - this column isnt contributing useful information for the classifier
df = df.drop(['lat', 'long', 'state_city'], axis=1)
df.columns

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'sqft_living15',
       'sqft_lot15'],
      dtype='object')

In [276]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor as RFR
from sklearn.metrics import mean_squared_error as mse
from sklearn.metrics import r2_score as r2

target_class = df['price']
df = df.drop(['price'], axis=1)

In [277]:
max_price = target_class.max()
print("Maximum house price:",max_price)
min_price = target_class.min()
print("Minimum house price:",min_price)
av_price = target_class.mean()
print("Average house price:",av_price)

Maximum house price: 7700000.0
Minimum house price: 75000.0
Average house price: 540088.1417665294


In [278]:
df.columns

Index(['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'sqft_living15',
       'sqft_lot15'],
      dtype='object')

In [279]:
# Predict house price using Random Forest
features = df.columns
data_train, data_test, target_train, target_test = train_test_split(df, target_class, test_size=0.2, random_state=1)

In [280]:
print(data_train.shape)
data_train.head()

(17290, 15)


bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
7291          3       1.75         2190      7021     1.0           0     2   
14835         3       2.50         2370      6840     2.0           0     0   
15880         2       1.00         1230      3800     1.0           0     0   
8812          4       2.25         2510      9963     1.0           0     0   
17220         3       1.00         1160      7491     1.0           0     0   

       condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
7291           4      7        1390            800      1953             0   
14835          3      9        2370              0      1987             0   
15880          3      7        1230              0      1928             0   
8812           4      9        2200            310      1967             0   
17220          4      6        1160              0      1917             0   

       sqft_living15  sqft_lot15  
7291            2180        7155  
14835           1590        4400  
15880           1610        3800  
8812            3110        9963  
17220           1800        2267

In [281]:
print(data_test.shape)
data_test.head()

(4323, 15)


bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  view  \
15544         4       2.75         2790      6600     2.0           0     0   
17454         3       2.25         1630      6449     1.0           0     0   
21548         2       1.50         2370    184231     2.0           0     0   
3427          4       2.50         2270      7665     2.0           0     0   
8809          3       1.00         1430      7599     1.5           0     0   

       condition  grade  sqft_above  sqft_basement  yr_built  yr_renovated  \
15544          3      9        2790              0      2000             0   
17454          3      7        1310            320      1986             0   
21548          3     11        2370              0      2005             0   
3427           3      9        2270              0      1986             0   
8809           4      6        1010            420      1930             0   

       sqft_living15  sqft_lot15  
15544           2900        6752  
17454           1620        7429  
21548           3860      151081  
3427            2450        8706  
8809            1290       10320

In [282]:
print("Target train size :", target_train.size)
print("Target test size :", target_test.size)

Target train size : 17290
Target test size : 4323


In [283]:
def getIntervals(data:pd.Series, num_intervals) -> list:
  return [(x,x+int((data.max()-data.min())/num_intervals)) for x in range(int(data.min()), int(data.max()), int((data.max()-data.min())/num_intervals))]

In [284]:
def findInterval(intervals:list, price):
  for interval in intervals:
    if interval[0] <= price <= interval[1]:
      return intervals.index(interval)
  return -1 # not found


def convert_prices(data:pd.Series, number_of_intervals:int)->pd.Series:
  intervals = getIntervals(data, number_of_intervals)
  data_intervals = data.apply(lambda x: findInterval(intervals, x))
  return data_intervals

target_intervals = convert_prices(target_class, 10)
print(set(target_intervals.values))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [291]:
# split target_intervals to train, test
target_train_intervals, target_test_intervals = train_test_split(target_intervals, test_size=0.2, random_state=1)
print(target_train_intervals.size)
print(target_test_intervals.size)

17290
4323


In [286]:
# Init the RFR Classifier
from sklearn.ensemble import RandomForestRegressor as RFR

rfr = RFR(n_estimators=100, random_state=1)
rfr.fit(data_train, target_train_intervals)

RandomForestRegressor(random_state=1)

In [263]:
# Predict the test set
target_pred_intervals = rfr.predict(data_test)

In [264]:
# Compare prediction to target_test_intervals
accuracy_score = r2(target_test_intervals, target_pred_intervals)
print("Accuracy score:", accuracy_score)

Accuracy score: 0.7008303538589614


In [292]:
# Check accuracies of different classifiers by num of estimators
accuracies = {}
for i in range(100, 1001, 100):
  rfr = RFR(n_estimators=i, random_state=1)
  rfr.fit(data_train, target_train_intervals)
  target_pred_intervals = rfr.predict(data_test)
  accuracies[i] = r2(target_test_intervals, target_pred_intervals)
  print("Accuracy score:", accuracies[i])
print(accuracies)

Accuracy score: 0.7010193977411667
Accuracy score: 0.7018939374625295
Accuracy score: 0.7005274285047542
Accuracy score: 0.7014042322980878
Accuracy score: 0.7021904823225382
Accuracy score: 0.7015551438365106
Accuracy score: 0.70138079215551
Accuracy score: 0.7017503610020439
Accuracy score: 0.701446881664619
Accuracy score: 0.7008303538589614
{100: 0.7010193977411667, 200: 0.7018939374625295, 300: 0.7005274285047542, 400: 0.7014042322980878, 500: 0.7021904823225382, 600: 0.7015551438365106, 700: 0.70138079215551, 800: 0.7017503610020439, 900: 0.701446881664619, 1000: 0.7008303538589614}


In [293]:
max_key = max(accuracies, key=accuracies.get)
print("The best accuracy is when the classifer used ", max_key, " estimators with accuracy: " ,accuracies[max_key])

The best accuracy is when the classifer used  500  estimators with accuracy:  0.7021904823225382


In [294]:
# Init ID3 classifier
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(data_train, target_train_intervals)

DecisionTreeClassifier(criterion='entropy')

In [295]:
# Predict on test set
id3_pred = clf.predict(data_test)
id3_pred

array([0, 0, 0, ..., 0, 2, 0])

In [296]:
# Get ID3 accuracy
from sklearn.metrics import accuracy_score, roc_auc_score
id3_score = accuracy_score(target_test_intervals, id3_pred)
print(id3_score)

0.8945176960444136


In [297]:
# Init LinearRegression classifier
from sklearn.linear_model import LinearRegression

reg = LinearRegression()
price_reg = reg.fit(data_train, target_train)
price_pred = price_reg.predict(data_test)
price_pred

array([ 727297.68410977,  312986.54189445,  853519.48368193, ...,
        463062.87675236, 1381599.57246012,  276748.07161185])

In [299]:
price_pred = list(map(round, price_pred))

In [300]:
price_reg_score = accuracy_score(target_test, price_pred)

print("Accuracy : ", price_reg_score)

Accuracy :  0.0


In [154]:
# BEDROOMS

#ASK AVIAD

# Init the Bayesian Classifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
gnb = GaussianNB()
gnb.fit(data_train, target_train_intervals)

scores = cross_val_score(gnb, df, target_intervals, cv=5)
print(scores)
print("Mean accuracy:", scores.mean())

[0.84987277 0.85773768 0.86167014 0.84798704 0.83433596]
Mean accuracy: 0.850320718158622


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:737: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  warnings.warn(


In [301]:
df = pd.read_csv("/content/kc_house_data.csv")
target_class = df['bedrooms']
data = df.drop(['bedrooms'], axis=1)
print(target_class)

data= data.drop(["lat", "long", "id", "zipcode", "date"],axis=1 )
print(data.columns)
print(set(target_class))


0        3
1        3
2        2
3        4
4        3
        ..
21608    3
21609    4
21610    2
21611    3
21612    2
Name: bedrooms, Length: 21613, dtype: int64
Index(['price', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront',
       'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built',
       'yr_renovated', 'sqft_living15', 'sqft_lot15'],
      dtype='object')
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 33}


In [302]:
data_train, data_test, target_train, target_test = train_test_split(data, target_class, test_size=0.2, random_state=42)


In [303]:
# Init LinearRegression classifier (bedrooms)
reg = LinearRegression().fit(data_train, target_train)
pred = reg.predict(data_test)
pred

array([3.43843462, 4.20577547, 3.80847562, ..., 3.68383883, 3.39275972,
       3.73151412])

In [304]:
# Round the prediction bedrooms number to match the original df values (int)
pred = list(map(round, pred))
reg_score = accuracy_score(target_test, pred)

print("Accuracy : ", reg_score)

Accuracy :  0.5808466342817488


In [306]:
# Random Forest - each iteration we drop another feature
accuracies = {}
bedroom_rfr = RFR(n_estimators=200, random_state=1)
for col in data_train.columns:
  bedroom_rfr_test = bedroom_rfr.fit(data_train.drop(col,axis=1), target_train)
  bedroom_rfr_pred = bedroom_rfr_test.predict(data_test.drop(col,axis=1))
  accuracies[col] = r2(target_test, bedroom_rfr_pred)
  print("Accuracy score:", accuracies[col])
print(accuracies)


Accuracy score: 0.5023757425905617
Accuracy score: 0.4761768626886077
Accuracy score: 0.49600020151547064
Accuracy score: 0.5030150266105748
Accuracy score: 0.49471825984188544
Accuracy score: 0.5016977516284391
Accuracy score: 0.5024384254325638
Accuracy score: 0.5004803081229889
Accuracy score: 0.4932516569910327
Accuracy score: 0.5024338193867899
Accuracy score: 0.502497505916903
Accuracy score: 0.47970592568039216
Accuracy score: 0.5014375945878408
Accuracy score: 0.494115807992879
Accuracy score: 0.5003315213462864
{'price': 0.5023757425905617, 'bathrooms': 0.4761768626886077, 'sqft_living': 0.49600020151547064, 'sqft_lot': 0.5030150266105748, 'floors': 0.49471825984188544, 'waterfront': 0.5016977516284391, 'view': 0.5024384254325638, 'condition': 0.5004803081229889, 'grade': 0.4932516569910327, 'sqft_above': 0.5024338193867899, 'sqft_basement': 0.502497505916903, 'yr_built': 0.47970592568039216, 'yr_renovated': 0.5014375945878408, 'sqft_living15': 0.494115807992879, 'sqft_lot15':

In [307]:
# Random Forest using complete DataSet
bedroom_rfr = RFR(n_estimators=200, random_state=1)
bedroom_rfr.fit(data_train, target_train)
bedroom_rfr_pred = bedroom_rfr.predict(data_test)
print("Accuracy score:", r2(target_test, bedroom_rfr_pred))

Accuracy score: 0.5018320371391515


In [309]:
# Init ID3 classifier (bedrooms)
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(data_train, target_train)

DecisionTreeClassifier(criterion='entropy')

In [310]:
# Predict on test set
id3_bedrooms_pred = clf.predict(data_test)
id3_bedrooms_pred

array([3, 3, 4, ..., 3, 4, 4])

In [311]:
# Get ID3 accuracy
id3_bedrooms_score = accuracy_score(target_test, id3_bedrooms_pred)
print(id3_bedrooms_score)

0.5262549155678927
